"""make_ingredient_id_nullable

Revision ID: 35b27c44622b
Revises: 20260121172825
Create Date: 2026-01-21 21:37:52.294103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35b27c44622b'
down_revision = '20260121172825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_menu_ingredients', schema=None) as batch_op:
        batch_op.alter_column('ingredient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('uq_menu_ingredient'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_menu_ingredients', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_menu_ingredient'), ['menu_id', 'ingredient_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('ingredient_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
