"""update detail food

Revision ID: 430db79bf89c
Revises: 4680d486c883
Create Date: 2026-01-09 02:23:57.828607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430db79bf89c'
down_revision = '4680d486c883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_menus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cooking_instructions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cooking_time_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_menus', schema=None) as batch_op:
        batch_op.drop_column('cooking_time_minutes')
        batch_op.drop_column('cooking_instructions')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
