"""Add image_url to food_menus

Revision ID: 5ab3337ac828
Revises: f3e4fbb3d30f
Create Date: 2026-01-04 21:47:06.406339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab3337ac828'
down_revision = 'f3e4fbb3d30f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_menus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_menus', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
