"""update preference

Revision ID: 78eec91b0dcf
Revises: 08f816e7ff29
Create Date: 2026-01-11 16:18:05.916116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78eec91b0dcf'
down_revision = '08f816e7ff29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lactation_phase', sa.String(length=20), nullable=True))
        batch_op.drop_column('lactation_ml')
        batch_op.drop_column('belly_circumference_cm')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('belly_circumference_cm', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lactation_ml', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('lactation_phase')

    # ### end Alembic commands ###
