"""Initial neon migration

Revision ID: 7be7cf7e1f17
Revises: 
Create Date: 2025-12-21 14:56:46.481928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7be7cf7e1f17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('alt_names', sa.Text(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('carbs_g', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('fat_g', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('food_menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('food_menu_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity_g', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['food_ingredients.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['food_menus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('menu_id', 'ingredient_id', name='uq_menu_ingredient')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('google_id', sa.String(length=100), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('food_meal_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('total_calories', sa.Integer(), nullable=False),
    sa.Column('total_protein_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_carbs_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_fat_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('servings', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('logged_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['food_menus.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('age_year', sa.Integer(), nullable=True),
    sa.Column('gestational_age_week', sa.Integer(), nullable=True),
    sa.Column('belly_circumference_cm', sa.Integer(), nullable=True),
    sa.Column('lila_cm', sa.Integer(), nullable=True),
    sa.Column('lactation_ml', sa.Integer(), nullable=True),
    sa.Column('food_prohibitions', mysql.JSON(), nullable=True),
    sa.Column('allergens', mysql.JSON(), nullable=True),
    sa.Column('calorie_target', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('food_meal_log_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_log_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity_g', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('carbs_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fat_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['food_ingredients.id'], ),
    sa.ForeignKeyConstraint(['meal_log_id'], ['food_meal_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_meal_log_items')
    op.drop_table('user_preferences')
    op.drop_table('food_meal_logs')
    op.drop_table('users')
    op.drop_table('food_menu_ingredients')
    op.drop_table('roles')
    op.drop_table('food_menus')
    op.drop_table('food_ingredients')
    # ### end Alembic commands ###
