"""add source_menu_id to food_logs

Revision ID: 8e278c460cbd
Revises: 
Create Date: 2025-11-08 09:17:50.638270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e278c460cbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_menu_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'food_menus', ['source_menu_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('source_menu_id')

    # ### end Alembic commands ###
