"""delete target call

Revision ID: ac76a70f04b0
Revises: 7be7cf7e1f17
Create Date: 2025-12-22 10:40:46.016010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac76a70f04b0'
down_revision = '7be7cf7e1f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('calorie_target')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calorie_target', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
