"""update usia kandungan 

Revision ID: c8df14ccb8b9
Revises: ac76a70f04b0
Create Date: 2025-12-30 01:47:47.896334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8df14ccb8b9'
down_revision = 'ac76a70f04b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hpht', sa.Date(), nullable=True))
        batch_op.drop_column('gestational_age_week')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gestational_age_week', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('hpht')

    # ### end Alembic commands ###
