"""add is_consumed to meal_log

Revision ID: f3e4fbb3d30f
Revises: c8df14ccb8b9
Create Date: 2026-01-04 21:12:48.700167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e4fbb3d30f'
down_revision = 'c8df14ccb8b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_meal_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_consumed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_meal_logs', schema=None) as batch_op:
        batch_op.drop_column('is_consumed')

    # ### end Alembic commands ###
