"""add target_role to food_menus

Revision ID: faa52b28062e
Revises: 6c0cbdde008b
Create Date: 2026-01-11 18:18:11.464072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa52b28062e'
down_revision = '6c0cbdde008b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_menus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_role', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_menus', schema=None) as batch_op:
        batch_op.drop_column('target_role')

    # ### end Alembic commands ###
